//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostelnew.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezerv()
        {
            this.Profits = new HashSet<Profit>();
        }
    
        public int id { get; set; }
        public Nullable<int> Worker_Id { get; set; }
        public Nullable<int> Bed_Id { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Bed Bed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profit> Profits { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
